# Generated by Django 2.1.7 on 2019-03-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuisine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_ID', models.IntegerField()),
                ('Restaurant_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=5000)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country_Code', models.IntegerField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Stars', models.FloatField()),
                ('Review_Count', models.FloatField()),
                ('is_open', models.IntegerField()),
                ('Categories', models.CharField(max_length=100)),
            ],
        ),
    ]
