# Generated by Django 2.1.7 on 2019-03-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='State',
            field=models.CharField(default='', max_length=100),
        ),
    ]
