# Generated by Django 2.1.7 on 2019-03-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro', '0002_auto_20190323_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Street',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
