# Generated by Django 2.1.7 on 2019-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro', '0003_restaurant_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Street',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Categories',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Country_Code',
            field=models.CharField(max_length=100),
        ),
    ]
