# Generated by Django 2.1.7 on 2019-03-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro', '0006_auto_20190324_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Review_Count',
            field=models.FloatField(null='true'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Stars',
            field=models.FloatField(null='true'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_open',
            field=models.IntegerField(null='true'),
        ),
    ]
