# Generated by Django 2.1.7 on 2019-03-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restro', '0007_auto_20190324_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_atrributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restro.Restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
